unzip_raw:
  zip_path: 'data/raw'
  hevc_path: 'data/external/hevc'

change_codec:
  h264_path: 'data/external/h264'

split_2m:
  vids_2m_path: 'data/interim/videos'

make_frames:
  labels_path: 'data/interim/labels'
  frames_path: 'data/processed/frames'

make_masks:
  masks_path: 'data/processed/masks'

split_dataset:
  test_frames_path: 'data/final/test/frames'
  test_masks_path: 'data/final/test/masks'
  train_frames_path: '../../yolov7-seg/yolov7_d2/datasets/train/images'
  train_masks_path: '../../yolov7-seg/yolov7_d2/datasets/train/outlined'
  valid_frames_path: '../../yolov7-seg/yolov7_d2/datasets/val/images'
  valid_masks_path: '../../yolov7-seg/yolov7_d2/datasets/val/outlined'
  valid_perc: 0.08
  test_perc: 0.15
 
train_model:
  model_arch: 'deeplabv3'
  in_features: 3
  out_features: 1
  learning_rate: 0.0003
  device: 'cpu'
  pin_memory: True
  load_model: False
  batch_size: 2
  num_epochs: 3
  num_workers: 2
  dest_height: 480
  dest_width: 640
  checkpoint_path : 'models/model.pth.tar'

evaluate_model:
  plots_path: 'reports/figures'
  metrics_path: 'reports/'
  threshold: 0.4
